name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1.5.0  # Replace with the latest version
      with:
        terraform_version: 1.13.0

    - name: Terraform Init
      run: terraform init

    - name: Configure MongoDB Atlas Credentials
      run: |
        echo "TF_VAR_mongodb_atlas_public_key=${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_atlas_private_key=${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_atlas_org_id=${{ secrets.MONGODB_ATLAS_ORG_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_mongodb_atlas_project_name=${{ secrets.MONGODB_ATLAS_PROJECT_NAME }}" >> $GITHUB_ENV

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
